### ISSUE TITLE
Error; cannot install the package

### ISSUE THREAD

**Issue by israelito3000** [sreeix/redis-proxy#24]
C:\Program Files\nodejs>npm install -g redis-proxy
npm WARN engine express@2.5.1: wanted: {"node":">= 0.4.1 < 0.7.0"} (current: {"n
ode":"0.12.2","npm":"2.7.4"})
npm WARN engine connect@1.8.7: wanted: {"node":">= 0.4.1 < 0.7.0"} (current: {"n
ode":"0.12.2","npm":"2.7.4"})
npm WARN excluding symbolic link lib\index.js -> jade.js

> hiredis@0.3.0 install C:\Users\ianido.AMAIISDOM\AppData\Roaming\npm\node_modul
es\redis-proxy\node_modules\hiredis
> node-gyp rebuild

C:\Users\ianido.AMAIISDOM\AppData\Roaming\npm\node_modules\redis-proxy\node_modu
les\hiredis>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\no
de_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" re
build )  else (rebuild)
'node' is not recognized as an internal or external command,
operable program or batch file.
npm WARN engine commander@0.2.1: wanted: {"node":">= 0.4.x < 0.7.0"} (current: {
"node":"0.12.2","npm":"2.7.4"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "redis-proxy"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! hiredis@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hiredis@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the hiredis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls hiredis
npm ERR! There is likely additional logging output above.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "redis-proxy"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4

npm ERR! Uncaught, unspecified "error" event.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\npm-debug.log

C:\Program Files\nodejs>

**Comment by sreeix** [comment]
Hi,
I do not have windows to test this. but looks like node is not in the path and if you put _node_ in the path it will run it correctly. Also if you do '<fullpath_to_node> server.js' it should work.
